//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Give_Aid
{
    using System;
    using System.Collections.Generic;
    
    public partial class donation
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string amount { get; set; }
        public string category { get; set; }
        public string bank { get; set; }
        public string iban { get; set; }
    }
}
