//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Give_Aid
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class giveaidEntities : DbContext
    {
        public giveaidEntities()
            : base("name=giveaidEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<donation> donations { get; set; }
        public virtual DbSet<partner> partners { get; set; }
        public virtual DbSet<register> registers { get; set; }
        public virtual DbSet<login1> login1 { get; set; }
    }
}
