//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Give_Aid
{
    using System;
    using System.Collections.Generic;
    
    public partial class register
    {
        public int id { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string companyname { get; set; }
        public string number { get; set; }
        public string txt { get; set; }
        public string img { get; set; }
    }
}
